project_name: dep-doctor
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/kyoshidajp/dep-doctor/cmd.Version={{.Version}}
      - -X github.com/kyoshidajp/dep-doctor/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
brews:
  - repository:
      owner: kyoshidajp
      name: homebrew-dep-doctor
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
