name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
